# Site settings
title: Wesley Beckner
name: Wesley Beckner
description: "Research and Teaching Website for Wesley Beckner."
baseurl: "http://wesleybeckner.github.io"
linkedin_username: wesley-beckner-b5631ab5
github_username: wesleybeckner
twitter_username: wesleyabeckner

# Build settings
markdown: kramdown
permalinks: pretty
highlighter: pygments
